# Generated by Django 2.2.20 on 2022-11-17 23:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentGraph', '0004_auto_20220924_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubt',
            name='edgeType',
        ),
        migrations.AddField(
            model_name='doubt',
            name='dateAdded',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='doubt',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edge',
            name='dateAdded',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='errorspecificfeedback',
            name='dateAdded',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='explanations',
            name='dateAdded',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='hints',
            name='dateAdded',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='node',
            name='dateAdded',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='problem',
            name='dateAdded',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='resolution',
            name='dateAdded',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dateAdded', models.DateField(default=datetime.date.today)),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnswerDoubt', to='studentGraph.Doubt')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentGraph.Problem')),
            ],
        ),
    ]
