# Generated by Django 2.2.20 on 2022-01-08 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeIdList', models.TextField()),
                ('studentId', models.TextField()),
                ('correctness', models.FloatField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentGraph.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('nodePositionX', models.IntegerField(default=-1)),
                ('nodePositionY', models.IntegerField(default=-1)),
                ('correctness', models.FloatField(default=0)),
                ('weigth', models.IntegerField(default=1)),
                ('visible', models.IntegerField(default=1)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentGraph.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctness', models.FloatField(default=0)),
                ('weigth', models.IntegerField(default=1)),
                ('destNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destNode', to='studentGraph.Node')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentGraph.Problem')),
                ('sourceNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceNode', to='studentGraph.Node')),
            ],
        ),
    ]
