# Generated by Django 2.2.20 on 2022-01-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentGraph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='alreadyCalculatedPos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='customPos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='isCalculatingPos',
            field=models.IntegerField(default=0),
        ),
    ]
