# Generated by Django 2.2.20 on 2023-10-03 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentGraph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node_votes_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positiveCounter', models.IntegerField(default=0)),
                ('negativeCounter', models.IntegerField(default=0)),
                ('dateAdded', models.DateTimeField()),
                ('dateModified', models.DateTimeField(blank=True, default=None, null=True)),
                ('historyDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('historyAction', models.TextField(blank=True, default=None, null=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodeVoteHistory', to='studentGraph.Node')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentGraph.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Node_votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positiveCounter', models.IntegerField(default=0)),
                ('negativeCounter', models.IntegerField(default=0)),
                ('dateAdded', models.DateTimeField()),
                ('dateModified', models.DateTimeField(blank=True, default=None, null=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodeVote', to='studentGraph.Node')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentGraph.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Edge_votes_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positiveCounter', models.IntegerField(default=0)),
                ('negativeCounter', models.IntegerField(default=0)),
                ('dateAdded', models.DateTimeField()),
                ('dateModified', models.DateTimeField(blank=True, default=None, null=True)),
                ('originalId', models.IntegerField(blank=True, default=None, null=True)),
                ('historyDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('historyAction', models.TextField(blank=True, default=None, null=True)),
                ('edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edgeVoteHistory', to='studentGraph.Edge')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentGraph.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Edge_votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positiveCounter', models.IntegerField(default=0)),
                ('negativeCounter', models.IntegerField(default=0)),
                ('dateAdded', models.DateTimeField()),
                ('dateModified', models.DateTimeField(blank=True, default=None, null=True)),
                ('edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edgeVote', to='studentGraph.Edge')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentGraph.Problem')),
            ],
        ),
    ]
