# Generated by Django 2.2.20 on 2022-08-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentGraph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='visible',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='node',
            name='alreadyCalculatedPos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='customPos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='isCalculatedPos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='isCalculatingPos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='multipleChoiceProblem',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='KnowledgeComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledgeComponentEdge', to='studentGraph.Edge')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledgeComponentNode', to='studentGraph.Node')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentGraph.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Hints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hintsEdge', to='studentGraph.Edge')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentGraph.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Explanations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanationsEdge', to='studentGraph.Edge')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentGraph.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorSpecificFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errorSpecificFeedbackEdge', to='studentGraph.Edge')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentGraph.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edgeType', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubtEdge', to='studentGraph.Edge')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubtNode', to='studentGraph.Node')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentGraph.Problem')),
            ],
        ),
    ]
