# Generated by Django 2.2.20 on 2022-01-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentGraph', '0002_auto_20220112_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='isCalculatedPos',
            field=models.IntegerField(default=0),
        ),
    ]
