# Generated by Django 2.2.20 on 2022-09-01 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentGraph', '0002_auto_20220828_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubt',
            name='order',
        ),
        migrations.RemoveField(
            model_name='errorspecificfeedback',
            name='order',
        ),
        migrations.RemoveField(
            model_name='explanations',
            name='order',
        ),
        migrations.RemoveField(
            model_name='hints',
            name='order',
        ),
        migrations.RemoveField(
            model_name='knowledgecomponent',
            name='order',
        ),
    ]
