# Generated by Django 2.2.20 on 2023-10-22 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentGraph', '0003_node_votes_history_originalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge_votes',
            name='lastStudentId',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='edge_votes_history',
            name='lastStudentId',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='node_votes',
            name='lastStudentId',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='node_votes_history',
            name='lastStudentId',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='AskedFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackType', models.TextField()),
                ('type', models.IntegerField(default=0)),
                ('studentId', models.TextField()),
                ('dateAdded', models.DateTimeField()),
                ('doubt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doubtNode', to='studentGraph.Doubt')),
                ('edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selectedEdge', to='studentGraph.Edge')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selectedNode', to='studentGraph.Node')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentGraph.Problem')),
            ],
        ),
    ]
