# Generated by Django 2.2.20 on 2022-01-12 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentGraph', '0003_problem_iscalculatedpos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='isCalculatedPos',
        ),
    ]
